# Generated by Django 4.1.1 on 2022-09-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regular_game', '0002_task_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
