# Generated by Django 4.1.1 on 2022-09-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regular_game', '0004_alter_player_time_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='next_task',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
