# Generated by Django 4.1.1 on 2022-09-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regular_game', '0006_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
