# Generated by Django 4.1.1 on 2022-09-28 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regular_game', '0007_player_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='best_solution',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='best_solution_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='regular_game.player'),
        ),
    ]
