# Generated by Django 4.2.5 on 2023-09-19 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game23', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('num', models.IntegerField()),
                ('text', models.TextField()),
                ('best_solution', models.TextField(null=True)),
                ('best_solution_player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game23.player')),
            ],
        ),
    ]
