# Generated by Django 4.2.5 on 2023-10-03 11:27

from django.db import migrations, models
import django.db.models.deletion
import game23.models


class Migration(migrations.Migration):
    dependencies = [
        ("game23", "0003_condition"),
    ]

    operations = [
        migrations.CreateModel(
            name="Difficulty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=15)),
                ("order", models.IntegerField()),
                ("avatar", models.CharField(max_length=20, unique=True)),
                ("avatar_url", models.URLField()),
                ("task_ok_score", models.IntegerField()),
                ("task_fail_score", models.IntegerField()),
                ("task_skip_score", models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name="player",
            name="difficulty",
            field=models.ForeignKey(
                default=game23.models.Difficulty.get_default_pk,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="game23.difficulty",
            ),
        ),
    ]
