# Generated by Django 4.2.5 on 2023-10-03 11:58

from django.db import migrations, models
import django.db.models.deletion
import game23.models


class Migration(migrations.Migration):
    dependencies = [
        ("game23", "0004_difficulty_player_difficulty"),
    ]

    operations = [
        migrations.AddField(
            model_name="condition",
            name="difficulty",
            field=models.ForeignKey(
                default=game23.models.Difficulty.get_default_pk,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="game23.difficulty",
            ),
        ),
    ]
