# Generated by Django 4.2.5 on 2023-10-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game23', '0005_condition_difficulty'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartialKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stand', models.IntegerField()),
                ('value', models.CharField(max_length=200)),
            ],
        ),
    ]
